# Generated by Django 5.1 on 2024-08-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_photos_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
