# Generated by Django 5.1 on 2024-08-31 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_photos_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='date_photo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
